name: GitHub python

on:
  push:
    branches:
      - main
      
  pull_request:
    types: [opened, synchronize]
    
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Show Python version
      run: 'python -v'
      
    - name: Show directory
      run: 'pwd'
      
    - name: List files
      run: 'ls -al'
      
    - name: Install Dependencies
      run: 'pip install -r requirements.txt'
      
    - name: Adds default product data to the database
      run: 'python db.py -a'

    - name: Prints all product data to the console
      run: 'python db.py -p'

    - name: Run tests
      run: echo "Tests to be added" #test
      
    
