name: GitHub python

on:
  push:
    branches:
      - main
      - jenk
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Show Python version
      run: 'python -v'
    - name: Show directory
      run: 'pwd'
    - name: List files
      run: 'ls -al'
    - name: Install Dependencies
      run: 'pip install -r requirements.txt'
    - name: Start db
      run: 'python db.py'
    - name: Start application
      run: 'python app.py'
    #- name: Test application
    #  run: 'mvn test'
